### ISSUE TITLE
Criteria for un-releasing software

### ISSUE THREAD

**Issue by pburkholder** [chef/chef-rfc#134]
Not sure if this is an RFC issue or something for Chef Inc., but do we have, or need, criteria for when we would unrelease stable downloads? 

Case in point, ChefDK 0.5.x on windows was essentially unusable since knife commands didn't work (https://github.com/chef/chef/issues/3272). Were we doing a disservice to Chef users by keeping 0.5.X MSIs on our downloads site if it was more likely to cause them grief than 0.4.0? In such cases when our software causes un-usability on major platforms, should we yank that release?  

If so, I'll be willing to write an RFC (or cajole someone else too). If that's out of scope for this process, then I shan't.

Thanks, 

Peter

**Comment by coderanger** [comment]
Last time with 12.2.0 it was done without a particular process. There was general agreement by those following the release issues that something needed to be done and eventually the un-publish was done as an ad-hoc thing. One of the action items from post-mortem at ChefConf (cc @jdmundrawala @btm) was to at least have a documented process for doing the yank so that would be a starting point.

**Comment by btm** [comment]
@pburkholder 

https://github.com/chef/chef-rfc/blob/master/rfc047-release-process.md#critical-regression-handling

Perhaps an update to that about yanking prior releases as well as the latest release?

**Comment by lamont-granquist** [comment]
One problem is deciding an objective criteria for when a bug is bad enough to yank.  Nearly every release will have regressions and bug fixes that troll someone.  

ChefDK also has that leading zero in the version which means that they get to take a mulligan every now and then and its expected to be in a state of higher flux.  And they need that because policyfiles and the chef command line utility are under development and it can't go to 1.x right now.

I'm also not sure this fixes the problem.  If nobody raised it as a critical issue and questioned if we should yank it, then having it written down that we should yank it doesn't actually make it happen.  An issue getting cut isn't necessarily enough with people who are busy and who read every one of them and roll a 1d20 saving throw against their workload to figure out how the problem should get addressed.  Unless someone is willing to argue for yanking it, then yanking won't magically happen just because its written down.  Basically I'm saying it would be more useful to be proactive about lobby for or doing yanking on critical bugs than it would be to have it written down that we should yank artifacts for critical bugs.

**Comment by pburkholder** [comment]
Thanks for all the comments. It seems that RFC 47 and 48 suffice for now to cover this issue, so I'll close.

I did notice that RFC48 doesn't have any path for critical regression and revocation of an issue -- issues simply stop at the 'Wait for PR' state, so perhaps it does need an update.  But I'll open that as a PR if I feel duly motivated.  Thanks, Peter
