### ISSUE TITLE
Document strategies and best-practices for dealing with CHEF-3694 and engage community to have existing cookbooks updated

### ISSUE THREAD

**Issue by pdf** [chef/chef-rfc#76]
CHEF-3694 deprecated resource cloning a long time ago, however very little has been done to deal with it in community cookbooks.  It seems likely that in part this is the result of a lack of any direction in how to do so.

Documentation should be provided with strategies to avoid resource cloning, using best-practices, and a concerted effort should be made to engage the community to implement them.

See #46 for prior discussion.

**Comment by pburkholder** [comment]
In case someone reading this has been living under a rock, the issue under discussion is https://tickets.opscode.com/browse/CHEF-3694.

**Comment by lamont-granquist** [comment]
skipping resource cloning warnings in the trivial case has already shipped.  because of the way the resource is cloned prior to it being passed the block of properties it was only possible to do this for extremely simple cases.

resource cloning is on the chopping block for chef 13.  we still need to do something around ambiguous notifications/subscribes to duplicated resources on the run_list.  my thought there would be to always prefer resolving to the resource in the current recipe if one exists without issuing a warning.  only in the case of a third recipe notifying duplicated resources would we warn about the ambiguity.

**Comment by martinb3** [comment]
Perhaps we could beef up the DSL to make it easier to locate an existing resource, so people wouldn't be tempted to declare duplicates, and instead look up an existing one.

**Comment by coderanger** [comment]
@martinb3 I think @jkeiser is currently working on an RFC to that effect.

**Comment by martinb3** [comment]
:+1: sweet.

**Comment by martinb3** [comment]
It's [on the agenda](https://github.com/chef/chef-community-irc-meetings/blob/master/2015-07-30-agenda.md) for today's meeting. Here's a [direct link to the RFC](https://github.com/chef/chef-rfc/pull/143).

**Comment by carpnick** [comment]
We used namespacing for cookbooks.


Required Resource convention we came up with:
```
file  "#{cookbook_name}_somefile" do
  file          somefile
  action        :create
end
```

FoodCritic Rule:
```
rule "EIS001", "Cookbook naming convention not being followed." do
  tags %w{correctness eis}
  metadata do |ast, filename|
    ast.xpath('//command[ident/@value="name"]').map do |declared_name|
      cb_name = declared_name.xpath('args_add_block/
        descendant::tstring_content[1]/@value').to_s
      declared_name unless cb_name == cb_name.downcase && cbs.select.any? { |key,value| cb_name.match(/#{value}/) }
      #compact gets rid of nils
    end.compact
  end
end
```

**Comment by lamont-granquist** [comment]
Duplicates concerns in #46 same comment I made when closing that one...

**Comment by habelson** [comment]
I have a use-case where I explicitly utilize resource cloning, that I think hasn't been discussed here. Of course, I am no expert, so if there is a better way... I am all ears.

My issue stems from the use of AWS OpsWorks which divides recipe run lists into various lifecycle stages. I can have a recipe that lays down configuration files for the "Configure" stage, and a separate one that deploys the app in the "Deploy" stage. However, if I want behavior such as 'if configuration file changes, then notify redeploy of app' it becomes more difficult. How I've achieved this using Chef 11 is to duplicate (minimal) the declaration of the application resource (in my case a docker_container) in the config recipe so that I can setup a notify :redeploy in the config file template.

Without resource cloning, I'm not sure how to achieve the same behavior.

**Comment by lamont-granquist** [comment]
you can reopen resources and modify them.

chef_rewind has done this for years:  https://github.com/thommay/chef-rewind

starting with 12.10.x there's support baked into chef for `edit_resource`:  https://docs.chef.io/dsl_recipe.html#edit-resource

resource cloning is the wrong way to do this.   the 3694 errors you are getting is a warning that you should not be doing this and its deprecated.  you'll break in chef 13 when its removed.
